<style> {
    margin: auto;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r library, echo=FALSE, message=FALSE, warning=FALSE}

library(tidyverse)
library(data.table)
library(descr)
library(RColorBrewer)
library(kableExtra)
library(knitr)
library(DT)
library(plotly)
library(ggthemes)
library(forcats)
library(leaflet)
library(sf)
library(rgdal)
library(treemapify)
library(reshape2)
library(randomcoloR)
library(survminer)
```

# Apêndice B {- #apendiceB}

\pagestyle{headings}



Critérios relativos ao escore de vulnerabilidade de aves migratórias a parques eólicos.  


```{r tab02, echo=FALSE, message=FALSE, warning=FALSE, encoding="UTF-8", paged.print=TRUE}

#install.packages('kableExtra')
library(kableExtra)
library(tidyverse)

tabela_7.2 <- read.csv2("dados/tabelas/Tabela_7.2.csv", encoding="UTF-8")
kbl(tabela_7.2,
             booktabs = TRUE,
             longtable = TRUE,
             # caption = 'Critérios relativos ao escore de vulnerabilidade de aves migratórias a parques eólicos.',
             col.names = c("Critério", "Conceito empregado")) %>%
             column_spec(1, italic = FALSE) %>% 
kable_styling(full_width = F, bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>% 
             column_spec(1, width = "5cm") %>% 
             column_spec(2, width = "10cm")

```





